version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.24.0
  - dependency-name: discord.js
    versions:
    - 12.5.2
